### ISSUE TITLE
2.2.8 CSS lenght maximum allowed line length is 998 octets

### ISSUE THREAD

**Issue by ilnytskyi** [mageplaza/magento-2-smtp#156] opened 2019-04-08 08:21 UTC
After upgrade to Magento 2.2.8
There are 2 new problems
1. Connections without authorization do not work. 
The message we have 
`Zend\Mail\Protocol\SmtpPluginManager::get was unable to fetch or create an instance for ""`
We had to change server configuration by using authorization.
2. `Exception message: maximum allowed line length is 998 octets`
As we noticed in the header `vendor/magento/module-email/view/frontend/email/header.html`
the styles that are loaded from `{{css file="css/email.css"}}` (default magento css is loaded) are minified. And the line contains more than 5000 characters. With xDebug we see line breaks "**\n**" during ` $transport->send($message);` but in SMTP logs we see one long line that cause a problem.
 (For now we ignore a line length, but it can cause a problem after switching to another server)
Any suggestions ?
Thanks

**Comment by Arthas78** [comment] 2019-04-10 02:27
Sorry for the late reply, Our working day has started.
Exactly, in Magento version 2.2.8, they used the previous Magento 2.3 flow to transport set up and send mail. Your error is caused by the authentication field set to 'None'. Try set to 'login'. Finally, the SMTP module is just an email module, it doesn't affect your email template problem at all. For more detail, you can disable the SMTP module and configured on dot-mailler(http://prntscr.com/n9ugxy), go out to the front end to check with the basic functions of Magento. If the problem persists, you should probably check your email template or configuration information

**Comment by Arthas78** [comment] 2019-04-17 04:30
Because not receiving feedback from you, I will close the issue here

**Closed by Arthas78** 2019-04-17 04:30 UTC
