### ISSUE TITLE
Mail won't send due to lack of PHP 7.2 or 7.3 support

### ISSUE THREAD

**Issue by tiledaily** [mageplaza/magento-2-smtp#209] opened 2019-11-28 05:58 UTC
Hi Mageplaza team,

First, thanks for a great extension -- we've enjoyed using it so far.  Upon upgrading to PHP 7.2 or 7.3, we notice that emails stop sending and the test email returns the following error:

`Deprecated Functionality: idn_to_ascii(): INTL_IDNA_VARIANT_2003 is deprecated in /home/tiledaily/public_html/vendor/zendframework/zend-validator/src/EmailAddress.php on line 560`

According to https://github.com/magento-engcom/php-7.2-support/issues/12, one of the Magento architects, @buskamoza, suggests that this issue is due to lack of PHP 7.2 support: https://github.com/magento-engcom/php-7.2-support/issues/24

**Comment by Arthas7895** [comment] 2019-11-28 10:09
It may due to your PHP version and Magento problem. The best way, you can down PHP version to 7.1 and test again

**Comment by waldok** [comment] 2019-11-28 10:44
It shouldn't be mageplaza/magento-2-smtp issue as we are using it with PHP 7.2 on production and have successfully tested with PHP 7.3. I think mageplaza/magento-2-smtp supports PHP 7.2 and 7.3

What is your Magento version?

**Comment by tiledaily** [comment] 2019-11-28 10:53
Thanks for this.  If I downgrade PHP, it works.  I'm on Magento 2.3.3 Open Source.  It _should_ work fine...

**Comment by Arthas7895** [comment] 2019-11-29 03:00
Exactly, this problem is due to the compatibility of Magento and PHP (not from the SMTP module). So if you want to solve thoroughly, you should start from 1 of 2 above. I have not tried Magento version 2.3.3 with PHP 7.3 yet, but it is fun if it works. in my opinion, for those who use Magento version 2.3 and have this problem, they should downgrade the PHP version
Have a nice day!

**Comment by waldok** [comment] 2019-11-29 09:06
Magento 2.3.3 officially supports PHP 7.3 - https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html
And it looks like it works for us without any issues so far.

Please make sure you had also upgraded all 3rd-party libraries.

**Comment by waldok** [comment] 2019-11-29 09:11
@tiledaily from the information you provided it looks like the problem is with zendframework/zend-validator.
What is the version of zendframework/zend-validator you have?
Maybe it was not updated. For example our development installation (which is working on PHP 7.3) has zendframework/zend-validator version 2.12.2.

**Comment by tiledaily** [comment] 2019-11-29 09:51
Thanks for the suggestions, all.  Here's what we've done:

1. Confirmed that our version of the Zend Validator is also 2.12.2
2. Confirmed our 3rd party modules are updated (We only use one other module from one other vendor aside from Mageplaza, and we only have a total of 3 custom functionality modules)
3. Installed a Magento-official patch which appears to deal with email-related issues in 2.3.3: https://community.magento.com/t5/Magento-DevBlog/Backward-incompatible-Changes-in-the-Mail-Library-for-Magento-2/ba-p/144787

Unfortunately for us, none of this solves our issue -- the same error occurs when using PHP 7.3 and does not occur when using 7.1.

We've got one more thing to try according to: https://github.com/magento/magento2/issues/19795#issuecomment-448492023 which is to check on our version of icu and see if it needs to be upgraded.  Will report back...

**Comment by Arthas7895** [comment] 2020-01-02 02:57
Thank you for your information, since this is a compatibility issue between Magento and the PHP version, we are also trying solutions on some of the proposed Magento forums. However, the best way currently (without fixing Core Magento) is to reduce the PHP version to 7.1. Hope Magento will fix it soon

**Comment by Arthas7895** [comment] 2020-01-13 10:51
Since it has been no more than 7 days for your response, I will close this issue here
Thank you very much!

**Closed by Arthas7895** 2020-01-13 10:51 UTC
