### ISSUE TITLE
SMTP Test mail works correctly, but orders mail gets error.

### ISSUE THREAD

**Issue by MBAHD** [mageplaza/magento-2-smtp#213] opened 2019-12-05 07:27 UTC
Hi, 
Im working on magento 2.2.5, after configuring SMTP extension the test mail works fine and send immediately, bun when someone makes an order the mail gives an error badge.
I checked the log and I think I am getting this error: 
main.CRITICAL: 5.5.4 Syntax: RCPT To:<address>

Note: I am using other Mageplaza extension and everything is working fine.
Thank you

**Comment by Arthas7895** [comment] 2019-12-05 09:01
If you have successfully sent the test email, I think the module is working fine. As far as I can see, the problem is at the TO field in your message. 
If you are experiencing this error with your email order then it is highly likely that your BCC or CC configuration is configured incorrectly(https://prnt.sc/q6hr42)

**Comment by MBAHD** [comment] 2019-12-05 09:06
Hi, 
I've checked the settings and everything looks fine, the contact for mails are sending successful, but order mails are giving this error.
![1](https://user-images.githubusercontent.com/58546544/70220434-a3726c00-1757-11ea-8c1a-b2f87b6a1213.png)
![2](https://user-images.githubusercontent.com/58546544/70220435-a3726c00-1757-11ea-818c-914a8b61dc6d.png)

**Comment by Arthas7895** [comment] 2019-12-06 03:45
In my opinion, it is related to your SMTP server settings(the high possibility is ISP installation)
You might need to check with your ISP for the settings for the SMTP server and change your settings accordingly.

**Comment by MBAHD** [comment] 2019-12-06 06:19
I don't think it has anything to do with the ISP, the very same mail address is logged into outlook sending and receiving with no issues, even Magento is sending test message and sending messages 
related to the contact us from, it's only about order mails which I am not finding a solution for.

**Comment by Arthas7895** [comment] 2019-12-23 07:38
It's strange because your log is clearly written as Syntax: RCPT To. This error is only caused by the email address that may include Unicode characters. Please delete the entire BCC and CC configuration fields and try again. I believe the problem is because an email address can't be verified
Besides, can you disable the SMTP module and try the test again on the dot-mailler of Magento 2 and sent me a result?

**Comment by Arthas7895** [comment] 2020-02-05 09:54
It's been over 7 days and I still haven't received a response from you, so I'll close this issue here
Thank you!

**Closed by Arthas7895** 2020-02-05 09:54 UTC
