### ISSUE TITLE
Magento 2.3 compatibility

### ISSUE THREAD

**Issue by afavata** [mageplaza/magento-2-smtp#129] opened 2018-12-04 15:49 UTC
Hi

is it compatible with Magento 2.3? I do not receive test email

**Comment by afavata** [comment] 2018-12-04 15:51
Hi

is it compatible with Magento 2.3?  I do not receive test email

**Comment by wilhelmpa** [comment] 2018-12-04 16:30
Let me answer this for Mageplaza. It's not compatible yet. But they are working on it.

**Comment by matthiashamacher** [comment] 2018-12-04 16:38
@wilhelmpa Any Idea when we could expect 2.3 compatibility?

We want to use Social Login, which requires SMTP but we are getting an 500er when sending emails especially "Forgot Password"-Mail (haven't tested all other posibilities). SMTP is not configured or enabled. In the Apache Logs there is following error:
`PHP Fatal error:  Class 'Zend_Application_Resource_Mail' not found in /var/www/html/vendor/mageplaza/module-smtp/Mail/Rse/Mail.php on line 31`

**Comment by Arthas78** [comment] 2018-12-05 02:03
We are doing on it for the compatible on Magento 2.3.
So that please don't rush to upgrade to 2.3 version. We're afraid of some odd error will occur

**Comment by ShapesGraphicStudio** [comment] 2018-12-10 14:58
Hi,
Any news on compatibility ?
I just installed latest version and I'm getting

**A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later.**

When trying to send a test email from config.

**Comment by Arthas78** [comment] 2018-12-11 02:02
Hi boys,
We are still looking for a solution so that SMTP module can run stably in Magento versions. Currently, we are having trouble with message handling on 2.3. It implements from a new interface that Magento 2.3 has just added. So we need more time to address these issues.
Please kindly understand!

**Comment by iindranil** [comment] 2018-12-11 11:01
Hello @Arthas78,

How much time it will take to fix this issue? or Any update on that please?

Thanks!

**Comment by Arthas78** [comment] 2018-12-12 03:59
@iindranil  Currently, we are still reading to find out the running stream of Magento 2.3. 
When we finish it, we will update it right here
https://github.com/mageplaza/magento-2-smtp

**Comment by vadim4err** [comment] 2018-12-12 12:06
With the release of Magento 2.3 agento Core team releasing a new version of Zend Framework 1.
They've removed Zend_Application module. https://devdocs.magento.com/guides/v2.3/release-notes/backward-incompatible-changes/
So how long it will take to fix the issue?

**Comment by Prizm4all** [comment] 2018-12-13 10:49
you state its compatible CE, EE 2.1.x - 2.3.x but its not. you might want to change this till it is compatible or people on 2.3 will prob get this error..

Autoload error: Module 'Mageplaza_Smtp' from '/home/sitename/public_html/app/code/Mageplaza/Smtp' has been already defined in '/home/sitename/public_html/vendor/mageplaza/module-smtp'.sitename@sitename.com

Just sayin.. :)

**Comment by AnatoleRozan** [comment] 2018-12-26 10:12
Up, is it now working in 2.3? Thanks.

**Comment by Arthas78** [comment] 2018-12-27 03:34
@AnatoleRozan We have completed the patch and are still testing it on the site

**Comment by jordanbergerman** [comment] 2018-12-30 22:12
@Arthas78 Hopefully this will be available soon. It doesn't work on Magento 2.2.7 CE,
`Please update your modules: Run \"composer install\" from the Magento root directory.\nThe following modules are outdated:\nMageplaza_Smtp db schema version: defined in codebase - 1.1.0, currently installed - 1.1.1\nMageplaza_Smtp db data version: defined in codebase - 1.1.0, currently installed - 1.1.1","1":"#0 \/home\/passionh\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(121): Magento\\Framework\\Module\\Plugin\\DbStatusValidator->beforeDispatch(Object(Magento\\Framework\\App\\FrontController\\Interceptor), Object(Magento\\Framework\\App\\Request\\Http))\n#1 \/home\/passionh\/public_html\/vendor\/magento\/module-page-cache\/Model\/App\/FrontController\/BuiltinPlugin.php(73): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#2 \/home\/passionh\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(135): Magento\\PageCache\\Model\\App\\Fro`

**Comment by himanshutecstub** [comment] 2019-01-01 10:19
I try to use this extension in Magento 2.3.0 but find below errors.
When run setup:upgrade than find below error
`{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Enabling [_all] is disabled in 6.0. As a replacement, you can use [copy_to] on mapping fields to create your own catch all field."}],"type":"illegal_argument_exception","reason":"Enabling [_all] is disabled in 6.0. As a replacement, you can use [copy_to] on mapping fields to create your own catch all field."},"status":400}`
When run setup:di:compile than find below error
`Class 'Mageplaza\Core\Helper\AbstractData' not found in /var/www/html20/app/code/Mageplaza/Smtp/Helper/Data.php on line 31`

**Comment by waldok** [comment] 2019-01-02 13:51
When are you going to release the fix for Magento 2.3.0? We either need to have the fix or will be forced to switch to another vendor within this week..

**Comment by Arthas78** [comment] 2019-01-03 02:06
@waldok We just finished the holiday season. If you want to create a ticket, I will send you a patch
https://www.mageplaza.com/contact.html

**Comment by kerlama** [comment] 2019-01-03 08:52
Why dont you release new version with patch included ?

**Comment by Arthas78** [comment] 2019-01-03 09:14
We are testing this patch with all previous Magento versions. Because Magento 2.3 uses a different thread than other versions, if this patch runs stably on previous versions we will release a new version.

**Comment by crankycyclops** [comment] 2019-01-08 13:50
I've been following this for about a month now, and I just want to say thank you to the developers for putting in the work to make this work on 2.3. I know it takes time to test everything properly, and I appreciate the effort :)

**Comment by Arthas78** [comment] 2019-01-11 09:51
@kerlama We have finished testing and are reviewing the code so the new version can be released soon

**Comment by Arthas78** [comment] 2019-01-14 03:09
@Dan547 yes, It is new updated version for SMTP module

**Comment by Arthas78** [comment] 2019-01-14 11:25
It is a new version of smtp but it has 1 file missing. We are trying to upload it

**Comment by lorenzofaresin** [comment] 2019-01-14 17:23
+1

**Comment by kerlama** [comment] 2019-01-15 11:14
Hi,
I have installed latest on 2.3.0 and while test email is working, order confirmation is not:

![screenshot_8](https://user-images.githubusercontent.com/4161312/51177050-e4069400-18be-11e9-922e-c17be5dcfe39.jpg)

And in system log:

[2019-01-15 11:13:43] main.ERROR: Zend\Mail\Transport\Smtp transport expects either a Sender or at least one From address in the Message; none provided [] []

**Comment by Arthas78** [comment] 2019-01-16 02:11
@kerlama As I mentioned above because our upload files are missing 1 file and 1 file is missing, that is why order mail isn't sent. If you need urgently, you can contact us (https://www.mageplaza.com/contact.html). I will assist you

**Comment by Arthas78** [comment] 2019-01-16 08:31
We have completed the update process. You can get new version SMTP here
https://github.com/mageplaza/magento-2-smtp

**Comment by dnradmin** [comment] 2019-01-16 18:38
Just uploaded this version and get this error....

PHP Fatal error:  Uncaught Error: Call to undefined method Mageplaza\Smtp\Helper\Data::getModuleConfig()

**Comment by dnradmin** [comment] 2019-01-16 18:39
Trying to send a test email which is throwing up the error.

**Comment by Arthas78** [comment] 2019-01-17 04:45
The new version of SMTP requires core 1.4 http://prntscr.com/m88x01
Please check your Core module again!

**Comment by kerlama** [comment] 2019-01-17 09:51
Hi @Arthas78 

I can confirm that everything is working now. 

@dnradmin 
get latest core module from https://github.com/mageplaza/module-core

**Comment by ssmadsen** [comment] 2019-01-17 14:57
Any one know if composer-package is updated with latest?

**Comment by michaellehmkuhl** [comment] 2019-01-17 15:01
@ssmadsen the current composer package worked for me yesterday. Thanks for getting this updated, Mageplaza team.

**Comment by ssmadsen** [comment] 2019-01-17 15:31
@michaellehmkuhl  
Apparently not all of us are that lucky.
Getting error this error "Zend\Mail\Protocol\SmtpPluginManager::get was unable to fetch or create an instance for" after setting up my sendgrid account within it.

**Comment by dnradmin** [comment] 2019-01-17 18:45
Just uploaded it all using composer, worked first time. Thank you to the Mageplaza team!

**Comment by McAlex220** [comment] 2019-01-17 18:47
Unfortunatly i'm getting error:
`main.CRITICAL: Zend\Mail\Protocol\SmtpPluginManager::get was unable to fetch or create an instance for  {"exception":"[object] (Magento\\Framework\\Exception\\MailException(code: 0): Zend\\Mail\\Protocol\\SmtpPluginManager::get was unable to fetch or create an instance for  at /vendor/mageplaza/module-smtp/Mail/Transport.php:118, Zend\\ServiceManager\\Exception\\ServiceNotFoundException(code: 0): Zend\\Mail\\Protocol\\SmtpPluginManager::get was unable to fetch or create an instance for  at /vendor/zendframework/zend-servicemanager/src/ServiceManager.php:555)"} []`

Using:
Magento 2.3.0
"module-core": "1.4.1"
"module-smtp": "1.2.9"

**Comment by Arthas78** [comment] 2019-01-18 02:48
@McAlex220 Please check the configuration information you entered (especially the Authentication field).

**Comment by McAlex220** [comment] 2019-01-18 12:53
Indeed! Strange, but it's working now. Thank you!

**Comment by McAlex220** [comment] 2019-01-19 01:16
Guys, still have problems. My hosting antispam blocks email with cyrillic subject: "550 Subject contains invalid characters." Even from default contact form. Seems to be an issue with this extension. Do you know how to solve this problem?

**Comment by Arthas78** [comment] 2019-01-19 03:31
@McAlex220 Try disabling the smtp module and re-testing it on dotmailer (it's a magento tool). If the error still occurs you should check with your host provider

**Comment by Arthas78** [comment] 2019-01-19 04:42
I tested the smtp module in the case of mail contact and found it working normally(http://prntscr.com/m96rt3) (http://prntscr.com/m96sdp). Are you sure it just can't send mail in the contact page? Please try with other cases like order mail and forgot password mail, etc. But to be sure you should test on dotmailler. It's a magento tool, if the problem persists you should check your host provider and your mail server

**Comment by McAlex220** [comment] 2019-01-19 15:52
Technical support of my hosting mail server says:
"When a message is rejected with "550 Subject contains invalid characters" the email subject will have non-ASCII characters, which is not allowed by the RFC. To include non-ASCII characters in subjects, the subject is required to be properly encoded, for example with UTF-8. Any normal mail client will automatically handle that for you, so it's likely a bug in a custom written script that generated the invalid subject."
Does it says something to you?

**Comment by JesKingDev** [comment] 2019-01-19 16:07
@McAlex220 please open a new issue for the Cyrillic problems so that can be tracked and resolved separately from support for 2.3

**Comment by McAlex220** [comment] 2019-01-19 18:16
@JesKingDev it still seems to be a compatibility problem with Magento 2.3 
Anyway, i've opened Cyrillic issue - https://github.com/mageplaza/magento-2-smtp/issues/135

**Comment by McAlex220** [comment] 2019-01-20 11:39
Yes. That's it! Thank you.:)

**Comment by McAlex220** [comment] 2019-01-20 13:13
One more thing. In emails i've recieved there is no sender name in headers.
I've test $message->getFrom() in Transport.php and there is no "name" as well - it's "NULL".
So i had to add below code to recieve "My Sender Name" in emails where you said in Transport.php:
```
foreach ($message->getFrom() as $address) {
  $email = $address->getEmail();
}
$message->setFrom($email, 'My Sender Name');
					
$message->getHeaders()->setEncoding('utf-8');
```
I'm not sure how to get Store General contact sender name properly. I think, you can do make this moment much better.

**Comment by Arthas78** [comment] 2019-01-20 16:32
I can still get data when using $message->getFrom(). However, if you want to configure the Sender, configure the return-path field and add the following code
https://prnt.sc/m9owv1

**Comment by McAlex220** [comment] 2019-01-20 16:58
@Arthas78 Not working - still only email in FROM field.  `$this->_returnPath[$storeId] ` returns only email, but not Sender name.

**Comment by Arthas78** [comment] 2019-01-21 02:21
exactly that is the settings of the system that allow you to only retrieve the email it can't retrieve the name (the default name is set to null), if you want to return the name, you can configure the following:
http://prntscr.com/m9v5y9
Also, when you get $message->getFrom() by default, it will retrieve the email for you, but the name is also set by default

**Comment by Arthas78** [comment] 2019-01-21 02:33
exactly that is the settings of the system that allow you to only retrieve the email it can't retrieve the name (the default name is set to null), if you want to return the name, you can configure the following:
http://prntscr.com/m9v9pi
Also, when you get $message->getFrom() by default, it will retrieve the email for you, but the name is also set by default

**Comment by Arthas78** [comment] 2019-01-21 05:46
Sorry, I sent the wrong code. This is the correct code
https://prnt.sc/m9wmgp

**Comment by McAlex220** [comment] 2019-01-21 11:17
Do you want to say that we can't get Sender Name from Store Email Addresses config?
Why not?
Something like this - https://magento.stackexchange.com/questions/125430/how-to-get-store-admin-email-address-and-name-in-magento-2-in-a-block ?

**Comment by Arthas78** [comment] 2019-01-21 11:31
You seem to be misunderstood between getFrom() and getSender() of the message. The config section of the return-path field(http://prntscr.com/ma0x77) can only enter an email so when you use $message->setSender()  you only have email data. but you can still pass more names in the setSender function (http://prntscr.com/ma0wcs)

**Comment by Arthas78** [comment] 2019-01-21 11:36
Your document section is to get the available config data. It is configured here
http://prntscr.com/ma10dl

**Comment by McAlex220** [comment] 2019-01-21 13:07
> Your document section is to get the available config data. It is configured here
That is my question. Why this extension doesn't use ANY sender name? For example, it can take sender name for Customer Support from config data you mensioned above.

**Comment by Arthas78** [comment] 2019-01-21 13:46
The Smtp is a module that has the function of configuring config information to send mail. The Smtp module only retrieves the messages that have been processed in the previous processing to send. Also, about return-path email problem is only handling the return task of the mailbox address to receive feedback when bounce when a problem occurs. We found it unnecessary to add a name attribute. However, if you want you can get the name for Customer Support and put it into the setSender() function ()

**Comment by McAlex220** [comment] 2019-01-21 14:11
I see... It's the problem with default contact form. Strange thing is that it doesn't set Sender name..

**Comment by Arthas78** [comment] 2019-01-21 14:34
I still do not understand where the problem you are having is? Contact mail is configured here(https://prnt.sc/ma3vav). You can disable the smtp module and try again with dotmailer on magento 2.3. It is the core magento's default mail flow

**Comment by McAlex220** [comment] 2019-01-21 15:14
When i fill default contact form - i recieve email without Sender Name, just sender email. I thought it's smtp module problem. But it's not. It's contact module problem - it doesn't set Sender name. That's strange for me, but it doesn't concern your module anymore. Thanks.)

**Comment by bartoll** [comment] 2019-01-21 23:57
There is still problem with compatibility with Magento 2.3.
I have installed fresh app, and your module in version 1.2.9.
Sending test email in configuration works well, but sending transaction email with order confirmation doesn't work.

**Comment by Arthas78** [comment] 2019-01-22 08:06
Ok, If there is no problem I will close this issue, once again you can download the version Smtp 1.2.9 to be compatible with Magento 2.3 here
https://github.com/mageplaza/magento-2-smtp
Thank you very much!

**Closed** 2019-01-22 08:07 UTC

**Comment by Arthas78** [comment] 2019-01-22 08:52
Please check your core module version and upgrade it if necessary

**Comment by ahmadbaig2002** [comment] 2019-02-02 16:59
> Magento 2.3 Error during set-up compile.
> `PHP Fatal error: Class 'Mageplaza\Core\Helper\AbstractData' not found in /app/code/Mageplaza/Smtp/Helper/Data.php on line 31`

This means Megaplaza core module is missing. Please use composer to install the SMTP extension or install Core module separately,

**Comment by ilnytskyi** [comment] 2019-04-03 09:50
@Arthas78
If I use **none** for auth - mails do not work. For servers with authorization it works.
`Zend\Mail\Protocol\SmtpPluginManager::get was unable to fetch or create an instance for ""`
I guess the problem is in Zend library ? Can it be fixed somehow ?

**Comment by linh232323** [comment] 2019-04-11 03:41
> @Arthas78
> If I use **none** for auth - mails do not work. For servers with authorization it works.
> `Zend\Mail\Protocol\SmtpPluginManager::get was unable to fetch or create an instance for ""`
> I guess the problem is in Zend library ? Can it be fixed somehow ?

I have same problem with None Authentication

**Comment by linh232323** [comment] 2019-04-11 05:01
> > @Arthas78
> > If I use **none** for auth - mails do not work. For servers with authorization it works.
> > `Zend\Mail\Protocol\SmtpPluginManager::get was unable to fetch or create an instance for ""`
> > I guess the problem is in Zend library ? Can it be fixed somehow ?
> 
> I have same problem with None Authentication

We can fix it by overwrite mageplaza/module-smtp file
File Path: vendor\mageplaza\module-smtp\Model\Config\Source\Authentication.php
change value of None from '' into 'smtp'.

The problem is from SmtpPluginManager . it only allows:
- crammd5
- login
- plain
- smtp (This is none)

**Comment by yoesoff** [comment] 2019-04-12 07:12
Hi everyone, I just started to learn  Magento (I am using 2.3.1) this week and I tried to install Mageplaza SMTP, but unfortunately It doesn't even shown in my Sidebar menu after composer require is done. any body know about how to (at least) show the Mageplaza on my Magento sidebar menu? 
I rised the question on Stackoverflow as well regarding this (my) issue.
 https://magento.stackexchange.com/questions/269830/mageplaza-menu-does-not-shown-on-sidebar

**Comment by sumeetmobiwebtech** [comment] 2019-06-01 10:16
Is anyone there ?
How to solve this error - ::Zend\Mail\Protocol\SmtpPluginManager::get was unable to fetch or create an instance for

**Comment by RalphVB** [comment] 2019-07-10 21:31
Hello :)

I've installed the SMTP module via composer and when I send a test mail it works without problem but when I try to register a new account in my site it crashes and sends this error:

PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method Magento\Framework\Phrase::isMultiPart() in /var/www/vhosts/demo.paycheckworks.com/demodocs/vendor/mageplaza/module-smtp/Mail/Transport.php:123

Any help, please?

**Comment by Arthas7895** [comment] 2019-07-11 04:20
I checked my site and saw it run normally || http://prntscr.com/odf2hb || http://prntscr.com/odf2sq
What version of SMTP are you using? You can remove this code(http://prntscr.com/odf4kb) and try again because it is compatible with our pdf invoice module and try again

**Comment by RalphVB** [comment] 2019-07-11 18:55
Thanks for your reply. I figured out it was a configuration error, now it's working.

**Comment by mannyqi** [comment] 2019-09-09 07:34
@RalphVB Can you recall what exactly you changed? Was it server side or in the magento2  backend?I'm sitting with the exact same error.

**Comment by RalphVB** [comment] 2019-09-09 18:46
@mannyqi It was the configuration at the Magento Backend of the SMTP Module. I did not touched the code. Right now I can't remember exactly which configuration was breaking my website, sorry man.

**Comment by mannyqi** [comment] 2019-09-09 19:23
@RalphVB No problem. Thank you. At least I've now narrowed it down to the Magento backend.

**Comment by mannyqi** [comment] 2019-09-11 06:39
In case anyone else stumbles on this thread like I did the issue was due to the Order Confirmation Templates being set to custom templates that was created on Magento 1 and transferred across to Magento 2 during the migration. I simply had to set them to the Magento 2 default templates.

**Comment by mykhailo-superiorseating** [comment] 2020-01-28 16:41
@mannyqi 
I have a solution!
In my case that were old m1 {{blocks}} in email templates for header and footer after the migration.
How to fix: [Migrate Magento1 Email templates to Magento2](https://magento.stackexchange.com/a/264472/83975)

**Comment by bartoll** [comment] 2020-01-28 22:13
Has anybody testes this SMTP module with new Magento 2.3.4?

**Comment by usman786cs** [comment] 2020-03-04 12:38
Getting this error. I've installed Magenplaz SMTP on Magento 2.3.4:

Content must be string or resource; received "Magento\Framework\Phrase". | Content must be string or resource; received "Magento\Framework\Phrase".
-- | --
Content must be string or resource; received "Magento\Framework\Phrase".
 
Any thoughts @lads

**Comment by ShapesGraphicStudio** [comment] 2020-03-04 12:59
Encoutered this yeasterday using php 7.2 for the command and got through it using php 7.1.
Hope this can help.

**Comment by usman786cs** [comment] 2020-03-04 14:41
> Encoutered this yeasterday using php 7.2 for the command and got through it using php 7.1.
> Hope this can help.

I can't use php7.1 on Magento2.3.4.

**Comment by RalphVB** [comment] 2020-03-04 16:51
@usman786cs Have you applied this [patch](https://community.magento.com/t5/Magento-DevBlog/Backward-incompatible-Changes-in-the-Mail-Library-for-Magento-2/ba-p/144787)? That error that you mention happened to me but I'm using the MegTrend MT Email extension and I solved it by checking in the template for the {{ directives like this }} to be {{ /closed }} correctly.
