### ISSUE TITLE
Test Emails Working & Order Emails Working but not newsletter emails

### ISSUE THREAD

**Issue by dineshmanne** [mageplaza/magento-2-smtp#200] opened 2019-10-31 10:03 UTC
Hi , I am using inmotionhosting email server to send emails in magento2. We configured your SMTP module. When we send test email and order emails those are delivering finely .

But when we deliver newsletter emails those are not delivering. Please help me on this.

I am using 465 port SSL mode.

**Comment by Arthas7895** [comment] 2019-11-01 03:08
I'm not sure what the problem is because you describe it yet to be thorough. However, if the send test and email orders both work, I think the SMTP configuration is correct and the module is working correctly.
First, check your email log to see if the newsletter emails are recorded there. If not, then I think you should check the newsletter form (maybe it's in error). If the newsletter emails have been recorded and the status is a success, please contact the mail server to check because the message has been sent to the mail server for processing but it cannot reach the recipient's IB. If the status is an error, it means the email has failed during sending to the mail server, you must check for errors in var/log/ system.log.

**Comment by Arthas7895** [comment] 2019-11-12 08:46
It's been over 7 days and I haven't received your response, I'll close the issue here
Thank you!

**Closed by Arthas7895** 2019-11-12 08:46 UTC
