### ISSUE TITLE
sometimes no order confirmation is sent

### ISSUE THREAD

**Issue by to8gal** [mageplaza/magento-2-smtp#177] opened 2019-07-02 07:17 UTC
Hi,

I am using Magento 2.2.4 and Mageplaza SMTP 1.1.1

I have noticed casually mails for order confirmation are not sent, I can not see trace of the not sent mail on the logs, and possibly this random behaviour is extended to other service but I can just notice the order confirmation one.

ShallI disable the sending native system? 

beside that I am really in the dark here

**Comment by Arthas7895** [comment] 2019-07-02 10:58
Your message does not appear on the email log, it is not sent (it is highly likely that your configuration information is wrong). You can check with the sent test email function.
You can read the guide here
https://docs.mageplaza.com/smtp-m2/

**Comment by to8gal** [comment] 2019-07-02 11:00
Of course I have read and used the test function, all good there, the site is professional and been up and working for months, but on a number of order some get unsent, I am using mandrill, and I see is no sent anywhere, for example on 4 orders yesterday just one is not sent

**Comment by Arthas7895** [comment] 2019-07-03 02:34
Please check in the email log whether your email orders have been sent. If the email status is successful, the email is sent, you should check the mail server to see it has been sent to the recipient's IB.
You should check the recipient's spam area, maybe the mail is in it

**Comment by to8gal** [comment] 2019-07-03 06:08
As wrote in the first post mail is not sent and not trace of it on the logs, I would like a more technical help, this is not helping.
As stated already sometimes mail are sent sometimes (like 10% of the cases) is not, but this is totallyrandom, and I can not figure out why, logs are empty, it can happen with all payment system I have (both paypal and Klarna) and all shipment method, I also check if logged in or not, or if the mail, or country of the customer, non of the above.

the only doubt is about the **Mail Sending Settings**, shall I put **Disable Email Communications** to Yes?

**Comment by Arthas7895** [comment] 2019-07-22 07:48
As you describe the problem, your messages are sometimes not sent (they are not saved in the email log). I'm afraid the problem is because you have created too many orders at the same time that your mail server cannot handle. You can check this with your mail server. Also if you put Disable Email Communications to Yes, all mail will not be sent

**Comment by Arthas7895** [comment] 2019-07-31 02:43
It's been 9 days without seeing any feedback from you, so I'll close this issue here
Thank you very much!

**Closed by Arthas7895** 2019-07-31 02:43 UTC
