### ISSUE TITLE
Magento 2.2.5: "Invalid sender data" in system.log after successful order. Transactional e-mail not sent.

### ISSUE THREAD

**Issue by JoshuaFlood** [mageplaza/magento-2-smtp#101] opened 2018-08-16 10:57 UTC
I was attempting to resolve this following #4, but the issue is closed and the suggested fixes don't work and the issue isn't being re-opened, so it makes more sense to create a new one.

Everything seems to work fine. The test e-mail is sent successfully using my desired SMTP server. The contact form works perfectly (though I'm not sure if this model is used for that).

Upon completing a successful transaction, the webpage alerts the user that an e-mail will be sent. Unfortunately, the e-mail is never recieved and system.log yields the error "Invalid sender data", which is the expected result at this point.

As advised in issue #80, I have installed [sashas777/bug-from-email](https://github.com/sashas777/bug-from-email) and it still doesn't work. I receive the same error as I did before the fix was installed. I'll point out here that @ymarc77 has already commented on issue #80 that they still recieve the error after the fix is applied.

During my discussions on issue #4, I was advised that I should install PHPMailer and test whether my server can connect to the smtp server independently.

I created the file 'testmail.php' in the project's root directory. It's contents are a trimmed-down version of the example contained within PHPMailer's github README file, as follows:

```
<?php
// Import PHPMailer classes into the global namespace
// These must be at the top of your script, not inside a function
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

//Load Composer's autoloader
require 'vendor/autoload.php';

$mail = new PHPMailer(true);                              // Passing `true` enables exceptions
try {
    //Server settings
    $mail->SMTPDebug = 2;                                 // Enable verbose debug output
    $mail->isSMTP();                                      // Set mailer to use SMTP
    $mail->Host = 'smtp1.example.com;smtp2.example.com';  // Specify main and backup SMTP servers
    $mail->SMTPAuth = true;                               // Enable SMTP authentication
    $mail->Username = 'user@example.com';                 // SMTP username
    $mail->Password = 'secret';                           // SMTP password
    $mail->SMTPSecure = 'tls';                            // Enable TLS encryption, `ssl` also accepted
    $mail->Port = 587;                                    // TCP port to connect to

    //Recipients
    $mail->setFrom('from@example.com', 'Mailer');
    $mail->addAddress('joe@example.net', 'Joe User');     // Add a recipient
    $mail->addReplyTo('info@example.com', 'Information');

    //Content
    $mail->isHTML(true);                                  // Set email format to HTML
    $mail->Subject = 'Here is the subject';
    $mail->Body    = 'This is the HTML message body <b>in bold!</b>';
    $mail->AltBody = 'This is the body in plain text for non-HTML mail clients';

    $mail->send();
    echo 'Message has been sent';
} catch (Exception $e) {
    echo 'Message could not be sent. Mailer Error: ', $mail->ErrorInfo;
}
```

I replaced the host with smtp.zoho.com, replaced the sender and return to address with the one configured in magento and replaced the recipient address with my own personal e-mail address.

I executed the script by issuing the command `php testmail.php` from the project directory. The message was sent successfully. I recieved no error logs and the e-mail appeared in my inbox as expected.

Once I've ensured that transactional e-mails are sent properly then everything is ready to switch this store over to production. Please help!

**Comment by JoshuaFlood** [comment] 2018-08-16 16:55
Or, at least, could someone explain how I can print the name of the 'from' address on the console, so that I can work out which address is being used and where it is being loaded from. Thanks.

**Comment by datvm231** [comment] 2018-08-17 01:34
Hi,

Please take a whole look at the issue that we mention at https://github.com/mageplaza/magento-2-smtp/issues/80
This is the problem from Magento 2.2.4 and 2.2.5, not from our SMTP extension. You can find many other issue on Magento about it as well, and lots of people reported that they need to disable Amazon modules that come with Magento to have order confirmation email sent properly.
For example, here: https://github.com/magento/magento2/issues/14952#issuecomment-404771460
Please try it.

**Comment by gixid192** [comment] 2018-08-17 01:58
@JoshuaFlood thanks for your detailed information.
Your server is working fine with Dotmailer meaning the mail server is functioning.

Now back to the issue with the 'from' address, it is in ` $mail->setFrom()` in your test script.
When you put it that way, it should work, but Magento handles this differently. I think it's `<From> from@example.com` or something, that's why it doesn't work.

@datvm231 also mentioned more information about the `From` issue, kindly take a look and also give it a try.
I would like to notice that you should make sure everything is updated after you change the code (meaning no cache, your server should use the new updated code).
Also, make sure you don't have any "related mail tools" enabling, I have seen some install 2 Smtp tools and expect them to work together, some have a tool that listens to sending emails function and that tool isn't compatible with our Smtp tool.

If you tried all the things and none is working so far.  We need to debug in your server, therefore, we will need SSH and Admin information.
If you think it is not worth it, you can try other Smtp tools, there are plenty of them on Github.

**Comment by JoshuaFlood** [comment] 2018-08-17 09:46
@datvm231 I understand what you are saying, but #80 just doesn't work for me. I had the SMTP module installed when I added the #80 bug fix, so I sort of expected the system to get a bit confused. Nonetheless, I executed the following commands:
```
setup:upgrade
setup:di:compile
indexer:reindex
cache:flush
setup:static-content:deploy en_GB -f
```

It didn't work, so I uninstalled the mageplaza module, deleting database tables and whatever else it created, ran the above series of commands again, then re-installed the SMTP module with the bug fix already enabled and ran the above commands again. Still no luck, still getting the same error in system.log.

I have tried manouvering your code to see if I can trace it back to wherever the address is being read from, but I guess I was getting confused looking for something like `$mail->setFrom()`, rather than `<From>`, so I was not successful.

Actually after noticing this error I was grep-ing and searching the database for any kind of incorrect e-mail. I had previously set some e-mails to 'no-reply-sales@...' and 'no-reply-support@...'. These addresses are not valid and so I would expect the email to fail. I had already updated these in the admin panel before installing the module, but they were still incorrect in the database, so I changed them to valid addresses, ran all of the above commands again and still no luck.

I have tried using grep to search for any case where I have provided an invalid e-mail address, but it seems like I've already corrected everything.

I'm happy to let you take a look at my server. Let me know where to send the details. Thanks.

**Comment by datvm231** [comment] 2018-08-17 10:17
Hi,

Please read more about the issue here https://github.com/magento/magento2/issues/14952

Also as I mentioned, please try disabling Amazon modules that come with Magento 2.2.4 and 2.2.5.
More specifically, please take a look at these:
https://github.com/magento/magento2/issues/14952#issuecomment-406231857
https://github.com/magento/magento2/issues/14952#issuecomment-410003697
https://github.com/amzn/amazon-payments-magento-2-plugin/issues/274

**Comment by JoshuaFlood** [comment] 2018-08-17 12:31
Ok there is one part I may have misunderstood. Before even looking for SMTP solutions I had disabled all of the mentioned modules and a few more... but I must have just skimmed those comments because I didn't actually uninstall them.

The list of disabled modules in my config are:
```
Magento_Dhl
Amazon_Core
Magento_Fedex
Magento_Authorizenet
Magento_NewRelicReporting
Klarna_Core
Amazon_Login
Amazon_Payment
Klarna_Ordermanagement
Magento_Ups
Magento_SampleData
Magento_Usps
Klarna_Kp
Dotdigitalgroup_Email
Magento_WishlistAnalytics
Shopial_Facebook
Temando_Shipping
Vertex_Tax
```

As I said, these were all disabled before I even knew the Mageplaza SMTP module existed. I did enable the dotdigital module to try testing, but that was after installing sashas bug fix and Mageplaza_Smtp.

I did even try applying the fix manually (I can't remember which repository/issue explained how to do it though).

I've read through every related issue in this repository, in the magento repository and I've read all I can find in the bug fix repository too. I've tried every fix mentioned in all referenced issues and still no luck.

I can uninstall the modules, but I don't know how without re-building the server. I've already re-built it multiple times due to all of the bugs that magento still has, so I'd rather not do it again.

I guess I could use another module, but if this one and the bug fix are written to solve precisely the problem that I'm having, then I don't see that they would yield better results.

**Comment by JoshuaFlood** [comment] 2018-08-17 12:53
Just tried uninstalling. According to Magento, `Amazon_Payment`, `Amazon_Login` and `Amazon_Core` are not installed modules, though I can clearly see that they are installed when I execute `module:status`... and I've tried running setup:di:compile to see if that gets rid of them. Uninstalling modules from other vendors works fine.

**Comment by JoshuaFlood** [comment] 2018-08-17 13:05
...and now my whole installation is broken. I can't run setup:upgrade because it tries to re-install Klarna, despite that I've added the "replace" parameter to my composer.json file as mentioned [here](https://github.com/magento/magento2/issues/14952#issuecomment-411504870).

The console yields the following error:

Installing schema... SQLSTATE[HY000]: General error: 1005 Can't create table `murky_magento`.`klarna_kco_order` (errno: 121 "Duplicate key on write or update"), query was: CREATE TABLE IF NOT EXISTS `klarna_kco_order` (
  `kco_order_id` int UNSIGNED NOT NULL auto_increment COMMENT 'Order Id' ,
  `klarna_checkout_id` varchar(255) NULL COMMENT 'Klarna Checkout Id' ,
  `klarna_reservation_id` varchar(255) NULL COMMENT 'Klarna Reservation Id' ,
  `order_id` int UNSIGNED NOT NULL COMMENT 'Order Id' ,
  `is_acknowledged` smallint NOT NULL default '0' COMMENT 'Is Acknowledged' ,
  PRIMARY KEY (`kco_order_id`),
  CONSTRAINT `KLARNA_KCO_ORDER_ORDER_ID_SALES_ORDER_ENTITY_ID` FOREIGN KEY (`order_id`) REFERENCES `sales_order` (`entity_id`) ON DELETE CASCADE
) COMMENT='Klarna Checkout Order' ENGINE=innodb charset=utf8 COLLATE=utf8_general_ci


I've tried all the commands I can think of but with no luck... so I guess that means I have to rebuild my server... again.

**Comment by JoshuaFlood** [comment] 2018-08-17 18:57
With some dodgy permission hacks, I've managed to convince composer to properly uninstall the modules, so now they don't exist at all in my distribution.

Still not working though...

Do you think you could look at my server please? Or at least tell me where your module assigns the 'from' parameter, so that I can create some console logs and debug it properly myself.

Thanks.

**Comment by gixid192** [comment] 2018-08-20 01:38
@JoshuaFlood You can send your credentials to our ticket system at this link: https://mageplaza.freshdesk.com/helpdesk/tickets

**Comment by datvm231** [comment] 2018-08-27 11:49
As we disscused on the ticket, the problem is caused by an invalid sender identity. Hence it couldn't retrieve sender name and email. I will close this issue here since the cause is from custom code.

**Closed by datvm231** 2018-08-27 11:49 UTC
