### ISSUE TITLE
Hi. Test Now Button is not working. i'm in magento 2.4 smtp 4.1.3.

### ISSUE THREAD

**Issue by NguyenvanLuc06081994** [mageplaza/magento-2-smtp#291] opened 2020-12-27 10:31 UTC
### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

**Comment by HuyPhuc98** [comment] 2020-12-28 02:52
Hi,

I reproduced your problem on the local page, as a result the Smtp module still works fine.
Would you please check back for me.
If the error persists, please provide a screenshot of the error for me.

Thank you!

**Comment by NguyenvanLuc06081994** [comment] 2020-12-28 12:09
thank you for your support. it's working. thank you very much.

**Comment by HuyPhuc98** [comment] 2020-12-29 02:29
Hi,

Since there are no more problems I will close the issue for now.
Thank you!

**Closed by HuyPhuc98** 2020-12-29 02:29 UTC
Labels: Issue
